name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.43.0-jammy
    steps:
      - name: Checkout the newest code
        uses: actions/checkout@v4
      - name: Set Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Run tests
        run: mvn test
        env:
          HOME: /root
      - name: Publish test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: target/cucumber-report.html

